type OstItem = {name: string, url: string | null}

export const ost: OstItem[] = [
  {name: 'No music', url: null},
  {name: 'Instrument of Surrender', url: '/Sea Power - Instrument of Surrender.m4a'},
  {name: 'Whirling-In-Rags, 8 AM', url: '/Sea Power - Whirling-In-Rags, 8 AM.m4a'},
  {name: 'Detective Arriving on the Scene', url: '/Sea Power - Detective Arriving on the Scene.m4a'},
  {name: 'Tiger King', url: '/Sea Power - Tiger King.m4a'},
  {name: 'Your Body Betrays Your Degeneracy', url: '/Sea Power - Your Body Betrays Your Degeneracy.m4a'},
  {name: 'Precinct 41 Major Crime Unit', url: '/Sea Power - Precinct 41 Major Crime Unit.m4a'},
  {name: 'The Insulindian Miracle', url: '/Sea Power - The Insulindian Miracle.m4a'},
  {name: 'Polyhedrons', url: '/Sea Power - Polyhedrons.m4a'},
  {name: 'Live With Me', url: '/Sea Power - Live With Me.m4a'},
  {name: 'The Field Autopsy', url: '/Sea Power - The Field Autopsy.m4a'},
  {name: 'Miss Oranje Disco Dancer', url: '/Sea Power - Miss Oranje Disco Dancer.m4a'},
  {name: 'Rue de Saint-Ghislaine 32B', url: '/Sea Power - Rue de Saint-Ghislaine 32B.m4a'},
  {name: 'The Doomed Commercial Area', url: '/Sea Power - The Doomed Commercial Area.m4a'},
  {name: 'The Cryptozoologists', url: '/Sea Power - The Cryptozoologists.m4a'},
  {name: 'Whirling-In-Rags, 8 PM', url: '/Sea Power - Whirling-In-Rags, 8 PM.m4a'},
  {name: 'Disco Elysium, Pt. 1', url: '/Sea Power - Disco Elysium, Pt. 1.m4a'},
  {name: 'Disco Elysium, Pt. 2', url: '/Sea Power - Disco Elysium, Pt. 2.m4a'},
  {name: 'Ecstatic Vibrations, Totally Transcendent', url: '/Sea Power - Ecstatic Vibrations, Totally Transcendent.m4a'},
  {name: 'Saint-Brune 1147 (Small Pinewood Church)', url: '/Sea Power - Saint-Brune 1147 (Small Pinewood Church).m4a'},
  {name: 'Martinaise, Terminal B', url: '/Sea Power - Martinaise, Terminal B.m4a'},
  {name: 'We Are Not Checkmated', url: '/Sea Power - We Are Not Checkmated.m4a'},
  {name: 'Hope in Work and Joy in Leisure', url: '/Sea Power - Hope in Work and Joy in Leisure.m4a'},
  {name: 'Burn, Baby, Burn', url: '/Sea Power - Burn, Baby, Burn.m4a'},
  {name: 'Whirling-In-Rags 12 PM', url: '/Sea Power - Whirling-In-Rags 12 PM.m4a'},
  {name: 'La Revacholiere', url: '/Sea Power - La Revacholiere.m4a'},
  {name: 'Krenel, Downwell, Somatosensor', url: '/Sea Power - Krenel, Downwell, Somatosensor.m4a'},
  {name: 'Off We Go Into The Wild Pale Yonder', url: '/Sea Power - Off We Go Into The Wild Pale Yonder.m4a'},
  {name: 'ZA/UM', url: '/Sea Power - ZA/UM.m4a'},
];
