export const skills = [
  'Logic',
  'Encyclopedia',
  'Rhetoric',
  'Drama',
  'Conceptualization',
  'Visual Calculus',
  'Volition',
  'Inland empire',
  'Empathy',
  'Authority',
  'Esprit De Corps',
  'Suggestion',
  'Endurance',
  'Physical Instrument',
  'Pain Threshold',
  'Electrochemistry',
  'Shivers',
  'Half-Light',
  'Hand/Eye Coordination',
  'Perception',
  'Reaction Speed',
  'Savoir Faire',
  'Interfacing',
  'Composure',
]

export const characters = [
  'You',
  'Acele',
  'Acele Berger',
  'Alain',
  'Alice DeMettrie',
  'Andre',
  'Annette',
  'Billie Méjean',
  'Bird\'s Nest Roy',
  'Call Me Mañana',
  'Charles Villedrouin',
  'Chester McLaine',
  'Cindy the SKULL',
  'Cleaning Lady',
  'Coalition Warship Archer',
  'Cuno',
  'Cunoesse',
  'DJ Flacio',
  'DJ Mesh',
  'Dennis',
  'Dolores Dei',
  'Don\'t Call Abigail',
  'Dora Ingerlund',
  'East-Insulindian Repeater Station',
  'Easy Leo',
  'Echo Maker',
  'Egg Head',
  'Elena',
  'Elizabeth Beaufort',
  'Ellis Kortenaer',
  'Eugene',
  'Evrart Claire',
  'Fat Angus',
  'Frittte clerk',
  'Fuck the World',
  'Garte',
  'Gary, the Cryptofascist',
  'Gaston Martin',
  'George',
  'Germaine van der Wijk',
  'Glen',
  'Gorący Kubek',
  'Horse-Faced Woman',
  'Idiot Doom Spiral',
  'Insulindian Phasmid',
  'Iosef Lilianovich Dros',
  'Isobel Sadie',
  'Jamrock Public Library',
  'Jean Vicquemare',
  'Jean-Luc Measurehead',
  'Jerry Lefitte',
  'Judit Minot',
  'Jules Pidieu',
  'Karl Holtzmann',
  'Katya',
  'Kim Kitsuragi',
  'Klaasje',
  'Kuuno de Ruyter',
  'Lena, the Cryptozoologist\'s wife',
  'Leonard Bellec',
  'Lilienne Carter',
  'Lilienne\'s Twin',
  'Lilienne\'s Other Twin',
  'Lillienne, the Net Picker',
  'Lily Carter',
  'Little Lily',
  'Mack Torson',
  'Man On Water Lock',
  'Man With Sunglasses',
  'Marianne LePlante',
  'Marielle Charpentier',
  'Maurice',
  'Measurehead\'s Babe',
  'Mega Rich Light-Bending Guy',
  'Mikael Heidelstam',
  'Miss Oranje Disco Dancer',
  'Morell, the Cryptozoologist',
  'Mysterious Pair of Eyes',
  'Neha',
  'Nix Gottlieb',
  'Noid',
  'Novelty Dicemaker',
  'Paledriver',
  'Pete Andre',
  'Phillis de Paule',
  'Pissf****t',
  'Plaisance',
  'Racist lorry driver',
  'Raul Kortenaer',
  'Real Estate Agent',
  'Rejoyce Leyton-Messier',
  'René Arnoux',
  'Rosemary',
  'Roustame Diodore',
  'Ruby, the Instigator',
  'Ruud Hoenkloewen',
  'Santiago S. John',
  'Scab Leader',
  'Shanky',
  'Siileng',
  'Sleeping Dockworker',
  'Smoker on the Balcony',
  'Soona Luukanen-Kilde',
  'Soona, the Programmer',
  'Steban, the Student Communist',
  'Sunday Friend',
  'Sylvie',
  'The Deserter',
  'The Gardener',
  'The Hanged Man',
  'The Pigs',
  'Theo',
  'Tiago',
  'Titus Hardie',
  'Tommy Le Homme',
  'Trant Heidelstam',
  'Ulixes',
  'Victor Méjean',
  'Washerwoman',
  'Working Class Corpse',
  'Working Class Woman',
  'Yvonne',
]

export const nameClass: Record<string, string> = {
  'Logic': 'text-intellect',
  'Encyclopedia': 'text-intellect',
  'Rhetoric': 'text-intellect',
  'Drama': 'text-intellect',
  'Conceptualization': 'text-intellect',
  'Visual Calculus': 'text-intellect',
  'Volition': 'text-psyche',
  'Inland empire': 'text-psyche',
  'Empathy': 'text-psyche',
  'Authority': 'text-psyche',
  'Esprit De Corps': 'text-psyche',
  'Suggestion': 'text-psyche',
  'Endurance': 'text-physique',
  'Physical Instrument': 'text-physique',
  'Pain Threshold': 'text-physique',
  'Electrochemistry': 'text-physique',
  'Shivers': 'text-physique',
  'Half-Light': 'text-physique',
  'Hand/Eye Coordination': 'text-motorics',
  'Perception': 'text-motorics',
  'Reaction Speed': 'text-motorics',
  'Savoir Faire': 'text-motorics',
  'Interfacing': 'text-motorics',
  'Composure': 'text-motorics',
}
