import "~/styles/globals.css";

import {type Metadata} from "next";
import {ThemeProvider} from '~/app/_components/ui/theme-provider';

import '@fontsource/libre-baskerville/400.css';
import '@fontsource/libre-baskerville/700.css';

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{rel: "icon", url: "/favicon.ico"}],
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider attribute="class" defaultTheme="dark">
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
