on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: GHCR login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Deploy
        env:
          UPDATE_POST_KEY: ${{ secrets.UPDATE_POST_KEY }}
        run: |
          curl --request POST \
               --url https://vhap-update.vanutp.dev/update \
               --header "Content-Type: application/json" \
               --data '{"key":"'$UPDATE_POST_KEY'"}' \
               --fail
